### ISSUE TITLE
Undefined symbols after updating to 1.3.1.1 - ZDKMockNetworkProtocol

### ISSUE THREAD

**Issue by jontelang** [zendesk/zendesk_sdk_ios#42]
Getting this after the most recent update

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ZDKMockNetworkProtocol", referenced from:
      _OBJC_CLASS_$_ZDKFailureProtocol in ZendeskSDK(ZDKFailureProtocol.o)
  "_OBJC_METACLASS_$_ZDKMockNetworkProtocol", referenced from:
      _OBJC_METACLASS_$_ZDKFailureProtocol in ZendeskSDK(ZDKFailureProtocol.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jaernouts** [comment]
Same issue here...

**Comment by TC94615** [comment]
Same issue here.
Downgrade to 1.3.0.1 is fine.
```
pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git', :tag => '1.3.0.1'
```

**Comment by jontelang** [comment]
@TC94615 Thanks, I tried something else and it told me I couldn't change version.

**Comment by tecknut** [comment]
Hey guys, we have just released a patch for this. Can you try again please and let me know if this solves the issue ?

**Comment by jaernouts** [comment]
@tecknut It's working again, thanks for the quick response!

**Comment by tecknut** [comment]
No problem @jontelang

**Comment by tecknut** [comment]
@jontelang @TC94615 I'm gonna mark this as closed as it's fixed in 1.3.1.2

**Comment by jontelang** [comment]
@tecknut Thanks, works fine.

**Comment by TC94615** [comment]
@tecknut works fine, thanks
