### ISSUE TITLE
Xcode 10.2 crash using Swift 4.2.1

### ISSUE THREAD

**Issue by davidohyer** [zendesk/zendesk_sdk_ios#483]
- SDK version: 2.3.0
- Xcode version: 10.2
- iOS or Simulator: iOS - iPad Mini A1490
- iOS Version: 12.2
- Swift version: 4.2

Steps to Reproduce:

1. Add Zendesk API to my project following the exact manual steps in the documentation.
2. Run app, the following error is thrown as soon as it runs:

dyld: Symbol not found: _$SBOWV
  Referenced from: /private/var/containers/Bundle/Application/1899180E-40DD-4571-9F0F-A4FBF6363141/MySmartBlindsEnterprise.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
  Expected in: /usr/lib/swift/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/1899180E-40DD-4571-9F0F-A4FBF6363141/MySmartBlindsEnterprise.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK

Any ideas? I've tried everything I can think of, been working on this one all day. Worked fine on Swift 3.0. Broke when I tried updating to Swift 4.2.

**Comment by KillianSmith0** [comment]
Hi @davidohyer 

Unfortunately the Supports 4.2 artefacts will not work on Xcode 10.2 beta. Your app will compile with the 4.2 artefacts, if you are using the latest official release of Xcode (10.1).

We have a task in our backlog to look into building artefacts on the more recent beta, we will update this issue once we look further into this.

Regards,
Killian
